name: Build PDF files for modified Typst sources
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filte changed typ files
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          list-files: shell
          filters: |
            typst:
              - added|modified: '**/*.typ'

      - name: Install fish shell
        if: ${{ steps.filter.outputs.typst == 'true' }}
        uses: fish-actions/install-fish@v1.1.0

      - name: Probe runner package cache
        if: ${{ steps.filter.outputs.typst == 'true' }}
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: cargo jq psutils
          version: 1.0

      - name: Install just from crates.io
        if: ${{ steps.filter.outputs.typst == 'true' }}
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just

      - name: Setup typst
        if: ${{ steps.filter.outputs.typst == 'true' }}
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Checkout schule package
        if: ${{ steps.filter.outputs.typst == 'true' }}
        uses: actions/checkout@v4
        with:
          repository: jneug/schule-typst
          # token: ${{ secrets.REGISTRY_TOKEN }}
          path: schule-typst

      - name: Install schule package to local package repository
        if: ${{ steps.filter.outputs.typst == 'true' }}
        run: |
            . schule-typst/scripts/setup

            SCHULE_NAME="${PKG_PREFIX}"
            SCHULE_VERSION="${VERSION}"
            TYPST_LOCAL="${XDG_DATA_HOME:-$HOME/.local/share}/typst/packages/local"
            echo "installing schule-typst to $TYPST_LOCAL/$SCHULE_NAME/$SCHULE_VERSION"
            mkdir -p "$TYPST_LOCAL/$SCHULE_NAME"
            mv schule-typst "$TYPST_LOCAL/$SCHULE_NAME/$SCHULE_VERSION"

      - name: Compile PDF files
        if: ${{ steps.filter.outputs.typst == 'true' }}
        run: |
          just compile ${{ steps.filter.outputs.typst_files }}

      - name: Upload artifacts to Google Drive
        if: ${{ steps.filter.outputs.typst == 'true' }}
        uses: guillep2k/github-to-drive@v1.0.0
        with:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          GDRIVE_FOLDERID: 1S9DGFP-N0ztTMLivW-KtCZfnuWsAZRF2
          GIT_ORIGIN: origin/main
          GIT_SUBDIR: ./pdf

